# go_binary(
#     name="bin",
#     cgo_enabled=False,
#     environment=parametrize("osx", "linux_go")
# )

go_binary(
    name="bin-osx",
    cgo_enabled=False,
    environment="osx"
)

go_binary(
    name="bin-linux",
    cgo_enabled=False,
    environment="linux_go"
)

go_package()
