go_mod()

# docker_image(
#     name="docker-linux",
#     extra_build_args=[
#         "ENVIRONMENT=@environment=linux_docker"
#     ]
# )

docker_image(
    name="docker-osx",
    extra_build_args=[
        "ENVIRONMENT=@environment=osx"
    ]
)
